require 'yaml'

VAGRANTFILE_API_VERSION = "2"
required_plugins = %w(vagrant-relaod)

unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

configuration = YAML::load(File.read("#{File.dirname(__FILE__)}/Hosts.yml"))
runPath = "#{File.dirname(__FILE__)}/" + configuration["path"]

require File.expand_path("#{runPath}/Hosts.rb")

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
        config.vm.boot_timeout = 1200
    Hosts.configure(config, configuration)
end
